### PR TITLE
Update apreader.py

### PR DESCRIPTION
**Pull request by J-ECLEMENT**
Add "Temps" ("Time" in French) to find channel name

### CODE REVIEW

**Review by leonbohmann — APPROVED** [review]

**Comment by leonbohmann** [comment]
Thanks for the PR. I merged it and it will be released with the next update 1.1.4.

**Comment by J-ECLEMENT** [comment]
You’re welcome. Thank you for your code, it is helping me with my project

**Comment by J-ECLEMENT** [comment]
Hi ! Any update on the 1.1.4 release ?

**Comment by leonbohmann** [comment]
Oh wow, some times has passed. I did not look into this any more since then. I will try to work on this at some point in the close future.

**Comment by J-ECLEMENT** [comment]
Thanks for getting back to me!
No worries, I understand 
For now I have a temporary patch in place, although it's not very clean.

**Pull request merged**
